### ISSUE TITLE
Is the genome available for using?

### ISSUE THREAD

**Issue by biozhangzhou** [sjswuitchik/duck_comp_gen#2]
Hello Dr. Wuitchik:
    Since your paper don't publish yet. I am wandering is your genome in the NCBI freely to use or what should I do to use it?

**Comment by tsackton** [comment]
We have a manuscript in preparation that we hope will be available as a preprint in the next two months, but in the mean time yes it is fine to use our genomes as a component of other work. We would ask that you don't publish any work that primarily describes our unpublished genomes, but using them in the context of a larger study is okay.

**Comment by biozhangzhou** [comment]
I got you. Thanks. Hope to see you new story soon.
