### ISSUE TITLE
Question about the CAT step

### ISSUE THREAD

**Issue by ld9866** [sjswuitchik/duck_comp_gen#3]
Dear developer:
We noticed that you used CAT in genome annotation, but because the software has not been maintained for a long time, some problems have been encountered, and our TransMapPsl step has been in a state of failure, may I ask how we can solve this problem?
Best day!
[log.txt](https://github.com/sjswuitchik/duck_comp_gen/files/13314057/log.txt)

**Comment by tsackton** [comment]
We never got CAT to run successfully in our local compute environment.
